-- FF-089: Fix OBJ-17 (Elizabeth Pass) signal_chips — expand assigned_agents to full outdoor + macro set.
-- Note: OUTDOOR_DROUGHT_MONITOR and OUTDOOR_SNOTEL_SNOWPACK do not exist in agent_configs;
-- corrected to the registered keys OUTDOOR_NOAA_DROUGHT_STATE and OUTDOOR_NRCS_SNOTEL.
UPDATE objective_profiles
SET assigned_agents = ARRAY[
  'OUTDOOR_NOAA_TEMP','OUTDOOR_NOAA_PRECIP','OUTDOOR_WINDY_API',
  'OUTDOOR_MOON_PHASE','OUTDOOR_DWR_HARVEST_UT','OUTDOOR_DWR_PERMITS_UT',
  'OUTDOOR_USGS_STREAMFLOW_STATE','OUTDOOR_INAT_OBSERVATIONS',
  'OUTDOOR_NOAA_FIRE_RISK','OUTDOOR_USFS_CLOSURE',
  'OUTDOOR_NOAA_DROUGHT_STATE','OUTDOOR_NRCS_SNOTEL',
  'OUTDOOR_NDVI_UTAH','OUTDOOR_PHENOLOGY_ASPEN',
  'OUTDOOR_TERRAIN_COMPOSITE','UNIV_FRED_CPI',
  'UNIV_FRED_FEDRATE','UNIV_EIA_GASPRICES'
]
WHERE objective_id = '29d41c7a-22e8-4c05-ad8b-f391aed1d06c';
